- name: get the username running the deploy
  command: whoami
  register: username_on_the_host
  changed_when: false
  check_mode: no

- name: test if user exists
  getent:
    database: passwd
    key: '{{ ansible_user }}'

- name: create dev directories
  become: true
  file:
    path: '{{ item }}'
    state: directory
    recurse: no
    mode: 0775
    owner: '{{ ansible_user }}'
    group: www-data
  with_items:
    - /var/firebird
    - /var/firebird/files
    - /var/firebird/indexes
    - /var/firebird/lock
    - /var/firebird/mailer
    - /var/firebird/testcase
    - /var/firebird/testcase/files
    - /var/firebird/testcase/indexes

- name: create home dev directories
  vars:
    username_path: '{{ username_on_the_host.stdout }}'
  become: true
  file:
    path: '{{ item }}'
    state: directory
    recurse: no
    owner: '{{ ansible_user }}'
    group: www-data
  with_items:
    - '/home/{{ username_path }}/firebird'
    - '/home/{{ username_path }}/firebird/dev'
    - '/home/{{ username_path }}/firebird/rc'
