- name: set php config options
  become: true
  ini_file:
    path: "/etc/php/{{ hostvars[inventory_hostname].php_version }}/{{ item[0] }}/php.ini"
    create: no
    section: '{{ item[1].section }}'
    option:  '{{ item[1].option }}'
    value:   '{{ item[1].value }}'
  with_nested:
    - [ cli, fpm ]
    -
      - { section: PHP,       option: error_reporting,         value: E_ALL }
      - { section: PHP,       option: display_errors,          value: 'On' }
      - { section: PHP,       option: display_startup_errors,  value: 'On' }
      - { section: PHP,       option: upload_max_filesize,     value: 20M }
      - { section: PHP,       option: post_max_size,           value: 20M }
      - { section: PHP,       option: output_buffering,        value: 'Off' }
      - { section: Session,   option: session.save_path,       value: '"0;660;/var/lib/php/sessions"' }
      - { section: Session,   option: session.gc_maxlifetime,  value: '86400' }
      - { section: Session,   option: session.cookie_lifetime, value: '86400' }
      - { section: Assertion, option: zend.assertions,         value: 1 }
  notify:
    - restart-php-fpm

- name: get xdebug version
  command:
    php -r "echo phpversion('xdebug');"
  check_mode: no
  changed_when: false
  register: xdebug_version

- name: add xdebug2 config
  include_tasks: xdebug_2.yml
  when: xdebug_version.stdout is version('3.0.0', '<')

- name: add xdebug3 config
  include_tasks: xdebug_3.yml
  when: xdebug_version.stdout is version('3.0.0', '>=')
