- name: install pkgs
  become: true
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - software-properties-common
    - curl

- name: add apt key for nodesource
  become: true
  apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key

- name: remove old node repos if present
  become: true
  apt_repository:
    repo: '{{ item }}'
    state: absent
    update_cache: no
  with_items:
    - 'ppa:chris-lea/node.js'
    - 'deb https://deb.nodesource.com/node_6.x {{ ansible_distribution_release }} main'
    - 'deb https://deb.nodesource.com/node_7.x {{ ansible_distribution_release }} main'
    - 'deb https://deb.nodesource.com/node_8.x {{ ansible_distribution_release }} main'
    - 'deb https://deb.nodesource.com/node_9.x {{ ansible_distribution_release }} main'
    - 'deb https://deb.nodesource.com/node_10.x {{ ansible_distribution_release }} main'

- name: add repo for nodesource
  become: true
  apt_repository:
    repo: 'deb https://deb.nodesource.com/node_11.x {{ ansible_distribution_release }} main'
    update_cache: no

- name: add git ppa's
  become: true
  apt_repository:
    repo: '{{ item }}'
    state: present
    update_cache: no
  with_items:
    - 'ppa:git-core/ppa'
    - 'ppa:ondrej/php'

- name: Update repositories cache
  become: true
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install ms fonts
  become: true
  apt: pkg=msttcorefonts state=latest
  notify:
    - clear fonts cache

- name: Upgrade all packages to the latest version
  become: true
  apt:
    upgrade: dist
    state: latest

- name: install pkgs
  become: true
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - automake
    - chromium-browser
    - cifs-utils
    - dia
    - dmtx-utils
    - gcc
    - gimp
    - git
    - gitk
    - google-perftools
    - graphviz
    - jpegoptim
    - kcachegrind
    - make
    - mc
    - nfs-common
    - nginx
    - nodejs
    - unrar
    - default-jre
    - password-gorilla
    - pgadmin3
    - php-fpm
    - php-cli
    - php-dev
    - php-gd
    - php-gmp
    - php-intl
    - php-json
    - php-mbstring
    - php-msgpack
    - php-mysql
    - php-pear
    - php-pgsql
    - php-redis
    - php-xdebug
    - php-xml
    - pngquant
    - postgresql
    - postgresql-contrib
    - python-setuptools
    - redis-server
    - ruby
    - sphinxsearch
    - openssh-server

- name: Clean local repository & remove unused dependency packages
  become: true
  apt:
    autoclean: yes
    autoremove: yes

- name: install less and csscomb
  become: true
  npm:
    name: '{{ item }}'
    global: yes
  with_items:
    - less
    - csscomb
